### ISSUE TITLE
Doctrine_Record_UnknownPropertyException: Unknown record property / related component "accept_licence" on "User"

### ISSUE THREAD

**Issue by zjhxmjl** [koweb/Vermis#13]
detail Error:
Doctrine_Record_UnknownPropertyException: Unknown record property / related component "accept_licence" on "User"
Backtrace:
```

#0 /home/zjhxmjl/public_html/Vermis/_vermis/lib/Doctrine/Doctrine/Record.php(1504): Doctrine_Record_Filter_Standard->filterSet(Object(User), 'accept_licence', '1')
#1 /home/zjhxmjl/public_html/Vermis/_vermis/lib/Doctrine/Doctrine/Record.php(1456): Doctrine_Record->_set('accept_licence', '1', true)
#2 /home/zjhxmjl/public_html/Vermis/_vermis/lib/Doctrine/Doctrine/Access.php(44): Doctrine_Record->set('accept_licence', '1')
#3 /home/zjhxmjl/public_html/Vermis/_vermis/app/controllers/Default/UsersController.php(341): Doctrine_Access->setArray(Array)
#4 /home/zjhxmjl/public_html/Vermis/_vermis/lib/Zend/Controller/Action.php(513): UsersController->registerAction()
#5 /home/zjhxmjl/public_html/Vermis/_vermis/lib/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('registerAction')
#6 /home/zjhxmjl/public_html/Vermis/_vermis/lib/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#7 /home/zjhxmjl/public_html/Vermis/_vermis/lib/FreeCode/Application.php(317): Zend_Controller_Front->dispatch()
#8 /home/zjhxmjl/public_html/Vermis/_vermis/app/models/Application.php(47): FreeCode_Application->dispatch()
#9 /home/zjhxmjl/public_html/Vermis/index.php(62): Application->execute()
#10 {main}
```

**Comment by omarpiani** [comment]
Solved in last commit.

**Comment by zjhxmjl** [comment]
awesome
